"""factory_core — the founder-owned, generic software-factory core.

A standalone, portable package that imports **nothing target-specific**. Every per-target
input (repo coordinates, working-agreement docs, compliance rules, role bindings, IdP config)
is data loaded at runtime through the adapter seams, never a code dependency. Deleting every
target pack leaves this package importable, testable, and green — that is the portability
guarantee, enforced by ``scripts/check_core_purity.py``.

Public surface:
  * manifest — the content-addressed, hash-chained, SoD-enforcing evidence ledger
  * target   — the TargetManifest loader (data in, never code)
  * adapters — the five ``typing.Protocol`` seams for all target contact
  * roles    — the capability/role model schema (grants are per-target data)
  * invariant_kernel — the neutral invariant IR, composition ledger, and a built-in
    graph-reachability analyzer (invariants carry their own start/forbidden roles + degree
    as data; the core names no target role, invariant, or annotation)
  * contract — neutral path normalization + forward/reverse FE<->BE contract diff, with a
    data-driven excuse classifier (inventories come from the adapter seams; rules are data)
  * completeness — a neutral inventory-row status lattice + falsifiable launch-readiness
    predicate (rows come from the adapter seams; the core owns only the aggregation)
  * comprehensiveness — a deterministic, injection-resistant intake-completeness gate: an
    ordered registry of structural field predicates (never an LLM); fields/thresholds are data
  * criticality — human-decided surface classes, declared side-effect closure, and fail-closed
    classification (unknown/unclassified is Critical)
  * checklist — evidence-backed gate items whose unchecked state remains a visible gap
  * tool_policy — signed Allowed / Sign-off-required / Verboten run capabilities with scoped
    pre-execution decisions and denial probes
  * test_disposition — authorization-based handling of formerly passing tests that now fail
  * build_plan — qualified recipe patterns plus disposable, authority-bound implementation IR
  * promotion — the oracle-adequacy × surface-criticality promotion decision: class-disposed
    evidence gaps, deterministic Critical evidence, specialist review, and candidate-bound
    Standard risk acceptance
  * provenance — fail-closed resolution of every downstream claim to a canonical item in the
    externally trusted product, architecture, or operational-maturity phase artifacts
  * independence — the graded independence ladder derived from the recorded arrangement, the
    per-agent model/version/directive record, and the structural-depth trade
  * monitors — spec-derived production monitors carrying their own resolvable authority, with
    class-scoped authorship and recorded-never-gated density
  * triage — alert triage that cannot silence the monitor it evaluated, plus earned notification
  * correction — the correction lane's red-now/green-now controls, the suspected-over-constraint
    rule for a red guard, and the reproduction requirement
"""

from __future__ import annotations

from factory_core.adapters import (
    ADAPTER_PROTOCOLS,
    ArtifactSink,
    ComplianceAdapter,
    IdpAdapter,
    KnowledgeAdapter,
    RepoAdapter,
)
from factory_core.build_plan import (
    BUILD_PLAN_SCHEMA_VERSION,
    CONSTRUCTION_BROWNFIELD,
    CONSTRUCTION_MODES,
    CONSTRUCTION_REGENERATE,
    PATTERN_CATALOG_SCHEMA_VERSION,
    BuildPlan,
    BuildPlanBundle,
    BuildPlanReport,
    BuildStep,
    OracleLink,
    PatternCatalog,
    PatternDefinition,
    verify_build_plan,
)
from factory_core.checklist import (
    ChecklistItemResult,
    ChecklistReport,
    normalize_checklist_id,
    verify_checklist,
)
from factory_core.completeness import (
    STATUS_DECLARED,
    STATUS_EXCUSED,
    STATUS_GAP,
    STATUS_PARTIAL,
    STATUS_PROVED,
    DimensionSummary,
    Inventory,
    InventoryRow,
    LaunchReadiness,
    launch_ready,
)
from factory_core.comprehensiveness import (
    VERDICT_COMPREHENSIVE,
    VERDICT_NEEDS_INFO,
    ComprehensivenessError,
    ComprehensivenessGate,
    ComprehensivenessResult,
    ConditionalSpec,
    FieldGap,
    SubstanceRequirement,
    SubstanceSpec,
    is_substantive,
)
from factory_core.contract import (
    CallEdge,
    Classification,
    ContractReport,
    Endpoint,
    ExcuseClassifier,
    ExcuseRule,
    ForwardReport,
    ReverseReport,
    check_contract,
    forward_contract,
    normalize_path,
    reverse_contract,
)
from factory_core.correction import (
    BASELINE_RESULT_FAILED,
    BASELINE_RESULT_PASSED,
    CONTROL_GREEN_NOW,
    CONTROL_RECOGNITION_CHECK,
    CONTROL_RED_NOW,
    CONTROL_ROLES,
    CONTROL_ROUTE_HUMAN,
    CONTROL_SATISFIED,
    CONTROL_SUSPECTED_OVER_CONSTRAINT,
    FAILURE_RELATION_DEFECT,
    FAILURE_RELATION_UNRELATED,
    LANE_CAPABILITY,
    LANE_CORRECTION,
    LANES,
    REPRODUCTION_IMPOSSIBLE,
    REPRODUCTION_NOT_REPRODUCED,
    REPRODUCTION_REPRODUCED,
    ControlClassification,
    ControlObservation,
    CorrectionRecord,
    CorrectionReport,
    ReproductionRecord,
    classify_control,
    normalize_control_role,
    verify_correction,
)
from factory_core.criticality import (
    BASE_REQUIRED_EVIDENCE_IDS,
    CRITICAL_APPROVER_FLOOR,
    CRITICALITY_CLASSES,
    CRITICALITY_COSMETIC,
    CRITICALITY_CRITICAL,
    CRITICALITY_STANDARD,
    CriticalityError,
    CriticalityProfile,
    CriticalityResolution,
    ResolvedSurface,
    SurfaceControl,
    normalize_label,
    resolve_criticality,
)
from factory_core.evidence import EvidenceIntegrity
from factory_core.independence import (
    INDEPENDENCE_MODERATE,
    INDEPENDENCE_STRONGER,
    INDEPENDENCE_STRONGEST,
    INDEPENDENCE_TIERS,
    INDEPENDENCE_WEAK,
    INDEPENDENCE_WEAKEST,
    RECORDED_ROLES,
    ROLE_CODER,
    ROLE_TESTER,
    ROLE_VALIDATOR,
    STRUCTURAL_MODE_IMPLEMENTATION_INFORMED,
    STRUCTURAL_MODE_ISOLATED,
    AgentIdentity,
    IndependenceRecord,
    IndependenceReport,
    StructuralModeRecord,
    derive_independence_tier,
    tier_rank,
    verify_independence,
)
from factory_core.invariant_kernel import (
    AnalysisResult,
    Analyzer,
    CapabilityDelta,
    CapabilityFlow,
    CapabilityLedger,
    ComposedModel,
    FidelityResult,
    GraphNode,
    InvariantKernel,
    ReachabilityAnalyzer,
    ReachabilityInvariant,
    SourceFacts,
    SourceFlowFact,
    Unsupported,
    Violation,
    check_delta_fidelity,
    load_delta,
)
from factory_core.invariant_kernel import analyze as analyze_invariants
from factory_core.manifest import (
    Ledger,
    LedgerEntry,
    SegregationError,
    SegregationPolicy,
    digest_bytes,
    digest_obj,
    verify_digest,
    verify_ledger,
)
from factory_core.monitors import (
    MONITOR_AUTHORSHIP_GENERATED,
    MONITOR_AUTHORSHIP_HUMAN,
    MONITOR_AUTHORSHIPS,
    MONITOR_DERIVATION_IMPLEMENTATION,
    MONITOR_DERIVATION_SPECIFICATION,
    MONITOR_DERIVATIONS,
    Monitor,
    MonitorSetReport,
    verify_monitor_set,
)
from factory_core.promotion import (
    DISPOSITION_BLOCK,
    DISPOSITION_GATE,
    DISPOSITION_PROMOTE,
    DISPOSITION_REPORT_AND_PROMOTE,
    DISPOSITION_RISK_ACCEPTED,
    GateOutcome,
    NamedEvidence,
    PromotionDecision,
    PromotionError,
    PromotionRequest,
    Quarantine,
    RiskAcceptance,
    SpecialistReview,
    SurfaceDecision,
    SurfaceObservation,
    decide_promotion,
    promotion_attestation_subject,
)
from factory_core.provenance import (
    ARTIFACT_ARCHITECTURE_SPECIFICATION,
    ARTIFACT_PRODUCT_SPECIFICATION,
    ARTIFACT_TESTING_MONITORING_STRATEGY,
    CLAIM_CONSTRAINT,
    CLAIM_MONITOR,
    CLAIM_REQUIREMENT,
    CLAIM_TASK,
    CLAIM_TEST_ASSERTION,
    PHASE_ARCHITECTURE,
    PHASE_ARTIFACT_NAMES,
    PHASE_OPERATIONAL_MATURITY,
    PHASE_PRODUCT_SPECIFICATION,
    PROVENANCE_GAP_PREFIXES,
    REQUIRED_PHASES,
    SUPPORTED_CLAIM_KINDS,
    IntentBackreference,
    IntentItem,
    PhaseArtifact,
    ProvenanceBundle,
    ProvenanceClaim,
    ProvenanceReport,
    ResolvedClaim,
    provenance_issue_is_gap,
    verify_intent_provenance,
)
from factory_core.registry import (
    Adapter,
    AdapterRegistry,
    AdapterResolutionError,
    Provider,
)
from factory_core.roles import (
    Capability,
    CapabilityCatalog,
    Grant,
    Role,
    RoleModel,
    RoleModelError,
)
from factory_core.target import (
    TargetManifest,
    TargetManifestError,
    load_target_manifest,
    load_target_manifest_bytes,
)
from factory_core.test_disposition import (
    TEST_ACTION_FIX_IMPLEMENTATION,
    TEST_ACTION_ROUTE_HUMAN,
    TEST_ACTION_UPDATE,
    TEST_CHANGE_AUTHORIZATION_SCHEMA_VERSION,
    TEST_CHANGE_RULING,
    ExistingTestDisposition,
    ExistingTestFailure,
    TestAssertionBinding,
    TestChangeAuthorization,
    TestSelection,
    dispose_existing_test_failure,
)
from factory_core.tool_policy import (
    AUTHORIZATION_MODES,
    AUTHORIZATION_RUN,
    AUTHORIZATION_USE,
    TOOL_POLICY_GAP_PREFIXES,
    TOOL_TIER_ALLOWED,
    TOOL_TIER_SIGNOFF_REQUIRED,
    TOOL_TIER_VERBOTEN,
    TOOL_TIERS,
    DenialProbe,
    ToolAuthorization,
    ToolInvocationDecision,
    ToolPolicy,
    ToolPolicyBundle,
    ToolPolicyReport,
    ToolRule,
    authorize_tool_invocation,
    tool_policy_issue_is_gap,
    verify_tool_policy,
)
from factory_core.triage import (
    NOTIFICATION_NOTIFY_HUMAN,
    NOTIFICATION_RECORD_ONLY,
    SILENCING_ACTIONS,
    TRIAGE_ACTION_DELETE_MONITOR,
    TRIAGE_ACTION_INVESTIGATE,
    TRIAGE_ACTION_PROPOSE_FIX,
    TRIAGE_ACTION_SILENCE_MONITOR,
    TRIAGE_ACTION_WEAKEN_THRESHOLD,
    TRIAGE_ACTIONS,
    TRIAGE_DISPOSITION_ALLOWED,
    TRIAGE_DISPOSITION_DENIED,
    TRIAGE_DISPOSITION_SPECIFICATION_DEFECT_REQUIRED,
    AlertAssessment,
    MonitorChangeRatification,
    NotificationDecision,
    TriageDecision,
    TriageRequest,
    decide_notification,
    decide_triage,
)

__version__ = "0.3.0"

__all__ = [
    "ADAPTER_PROTOCOLS",
    "ARTIFACT_ARCHITECTURE_SPECIFICATION",
    "ARTIFACT_PRODUCT_SPECIFICATION",
    "ARTIFACT_TESTING_MONITORING_STRATEGY",
    "AUTHORIZATION_MODES",
    "AUTHORIZATION_RUN",
    "AUTHORIZATION_USE",
    "Adapter",
    "AdapterRegistry",
    "AdapterResolutionError",
    "AgentIdentity",
    "AlertAssessment",
    "AnalysisResult",
    "Analyzer",
    "ArtifactSink",
    "BASELINE_RESULT_FAILED",
    "BASELINE_RESULT_PASSED",
    "BASE_REQUIRED_EVIDENCE_IDS",
    "BUILD_PLAN_SCHEMA_VERSION",
    "CLAIM_MONITOR",
    "CONTROL_GREEN_NOW",
    "CONTROL_RECOGNITION_CHECK",
    "CONTROL_RED_NOW",
    "CONTROL_ROLES",
    "CONTROL_ROUTE_HUMAN",
    "CONTROL_SATISFIED",
    "CONTROL_SUSPECTED_OVER_CONSTRAINT",
    "CRITICALITY_CLASSES",
    "CRITICALITY_COSMETIC",
    "CRITICALITY_CRITICAL",
    "CRITICALITY_STANDARD",
    "CRITICAL_APPROVER_FLOOR",
    "CallEdge",
    "CLAIM_CONSTRAINT",
    "CLAIM_REQUIREMENT",
    "CLAIM_TASK",
    "CLAIM_TEST_ASSERTION",
    "Capability",
    "CapabilityCatalog",
    "CapabilityDelta",
    "CapabilityFlow",
    "CapabilityLedger",
    "BuildPlan",
    "BuildPlanBundle",
    "BuildPlanReport",
    "BuildStep",
    "ChecklistItemResult",
    "ChecklistReport",
    "Classification",
    "ComplianceAdapter",
    "ComposedModel",
    "ComprehensivenessError",
    "ComprehensivenessGate",
    "ComprehensivenessResult",
    "ConditionalSpec",
    "CONSTRUCTION_BROWNFIELD",
    "CONSTRUCTION_MODES",
    "CONSTRUCTION_REGENERATE",
    "ContractReport",
    "ControlClassification",
    "ControlObservation",
    "CorrectionRecord",
    "CorrectionReport",
    "CriticalityError",
    "CriticalityProfile",
    "CriticalityResolution",
    "DISPOSITION_BLOCK",
    "DISPOSITION_GATE",
    "DISPOSITION_PROMOTE",
    "DISPOSITION_REPORT_AND_PROMOTE",
    "DISPOSITION_RISK_ACCEPTED",
    "DenialProbe",
    "DimensionSummary",
    "Endpoint",
    "EvidenceIntegrity",
    "ExistingTestDisposition",
    "ExistingTestFailure",
    "ExcuseClassifier",
    "ExcuseRule",
    "FAILURE_RELATION_DEFECT",
    "FAILURE_RELATION_UNRELATED",
    "FidelityResult",
    "FieldGap",
    "ForwardReport",
    "GateOutcome",
    "Grant",
    "GraphNode",
    "INDEPENDENCE_MODERATE",
    "INDEPENDENCE_STRONGER",
    "INDEPENDENCE_STRONGEST",
    "INDEPENDENCE_TIERS",
    "INDEPENDENCE_WEAK",
    "INDEPENDENCE_WEAKEST",
    "IdpAdapter",
    "IndependenceRecord",
    "IndependenceReport",
    "Inventory",
    "InventoryRow",
    "IntentBackreference",
    "IntentItem",
    "InvariantKernel",
    "KnowledgeAdapter",
    "LANES",
    "LANE_CAPABILITY",
    "LANE_CORRECTION",
    "LaunchReadiness",
    "Ledger",
    "LedgerEntry",
    "MONITOR_AUTHORSHIPS",
    "MONITOR_AUTHORSHIP_GENERATED",
    "MONITOR_AUTHORSHIP_HUMAN",
    "MONITOR_DERIVATIONS",
    "MONITOR_DERIVATION_IMPLEMENTATION",
    "MONITOR_DERIVATION_SPECIFICATION",
    "Monitor",
    "MonitorChangeRatification",
    "MonitorSetReport",
    "NOTIFICATION_NOTIFY_HUMAN",
    "NOTIFICATION_RECORD_ONLY",
    "NamedEvidence",
    "NotificationDecision",
    "OracleLink",
    "PHASE_ARCHITECTURE",
    "PHASE_ARTIFACT_NAMES",
    "PHASE_OPERATIONAL_MATURITY",
    "PHASE_PRODUCT_SPECIFICATION",
    "PATTERN_CATALOG_SCHEMA_VERSION",
    "PROVENANCE_GAP_PREFIXES",
    "PhaseArtifact",
    "PatternCatalog",
    "PatternDefinition",
    "PromotionDecision",
    "PromotionError",
    "PromotionRequest",
    "ProvenanceBundle",
    "ProvenanceClaim",
    "ProvenanceReport",
    "Quarantine",
    "Provider",
    "RECORDED_ROLES",
    "REPRODUCTION_IMPOSSIBLE",
    "REPRODUCTION_NOT_REPRODUCED",
    "REPRODUCTION_REPRODUCED",
    "ROLE_CODER",
    "ROLE_TESTER",
    "ROLE_VALIDATOR",
    "ReachabilityAnalyzer",
    "ReachabilityInvariant",
    "REQUIRED_PHASES",
    "RepoAdapter",
    "ReproductionRecord",
    "ReverseReport",
    "Role",
    "RoleModel",
    "RoleModelError",
    "ResolvedClaim",
    "ResolvedSurface",
    "RiskAcceptance",
    "SILENCING_ACTIONS",
    "STATUS_DECLARED",
    "STATUS_EXCUSED",
    "STATUS_GAP",
    "STATUS_PARTIAL",
    "STATUS_PROVED",
    "STRUCTURAL_MODE_IMPLEMENTATION_INFORMED",
    "STRUCTURAL_MODE_ISOLATED",
    "SegregationError",
    "SegregationPolicy",
    "SourceFacts",
    "SourceFlowFact",
    "SpecialistReview",
    "StructuralModeRecord",
    "SubstanceRequirement",
    "SubstanceSpec",
    "SUPPORTED_CLAIM_KINDS",
    "SurfaceControl",
    "SurfaceDecision",
    "SurfaceObservation",
    "TEST_ACTION_FIX_IMPLEMENTATION",
    "TEST_ACTION_ROUTE_HUMAN",
    "TEST_ACTION_UPDATE",
    "TEST_CHANGE_AUTHORIZATION_SCHEMA_VERSION",
    "TEST_CHANGE_RULING",
    "TOOL_POLICY_GAP_PREFIXES",
    "TOOL_TIER_ALLOWED",
    "TOOL_TIER_SIGNOFF_REQUIRED",
    "TOOL_TIER_VERBOTEN",
    "TOOL_TIERS",
    "TRIAGE_ACTIONS",
    "TRIAGE_ACTION_DELETE_MONITOR",
    "TRIAGE_ACTION_INVESTIGATE",
    "TRIAGE_ACTION_PROPOSE_FIX",
    "TRIAGE_ACTION_SILENCE_MONITOR",
    "TRIAGE_ACTION_WEAKEN_THRESHOLD",
    "TRIAGE_DISPOSITION_ALLOWED",
    "TRIAGE_DISPOSITION_DENIED",
    "TRIAGE_DISPOSITION_SPECIFICATION_DEFECT_REQUIRED",
    "TargetManifest",
    "TargetManifestError",
    "TestAssertionBinding",
    "TestChangeAuthorization",
    "TestSelection",
    "ToolAuthorization",
    "ToolInvocationDecision",
    "ToolPolicy",
    "ToolPolicyBundle",
    "ToolPolicyReport",
    "ToolRule",
    "TriageDecision",
    "TriageRequest",
    "Unsupported",
    "VERDICT_COMPREHENSIVE",
    "VERDICT_NEEDS_INFO",
    "Violation",
    "analyze_invariants",
    "authorize_tool_invocation",
    "check_contract",
    "check_delta_fidelity",
    "classify_control",
    "decide_notification",
    "decide_promotion",
    "decide_triage",
    "derive_independence_tier",
    "digest_bytes",
    "digest_obj",
    "dispose_existing_test_failure",
    "forward_contract",
    "is_substantive",
    "launch_ready",
    "load_delta",
    "load_target_manifest",
    "load_target_manifest_bytes",
    "normalize_checklist_id",
    "normalize_control_role",
    "normalize_label",
    "normalize_path",
    "promotion_attestation_subject",
    "provenance_issue_is_gap",
    "resolve_criticality",
    "reverse_contract",
    "tier_rank",
    "tool_policy_issue_is_gap",
    "verify_checklist",
    "verify_build_plan",
    "verify_correction",
    "verify_digest",
    "verify_independence",
    "verify_intent_provenance",
    "verify_ledger",
    "verify_monitor_set",
    "verify_tool_policy",
    "__version__",
]
